# Worker Deployment - THIS is what KEDA scales
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: keda-app:latest
          imagePullPolicy: Never
          command: ["python", "worker.py"]
          env:
            - name: REDIS_DB_HOST
              value: "redis"
            - name: QUEUE_NAME
              value: "order-queue"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
